# Generated by Django 5.2.1 on 2025-05-31 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre descriptivo del punto de monitoreo, ej: 'Patio Central USM', 'Laboratorio A1'", max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional o detalles sobre la ubicación del punto.', null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del punto de monitoreo.', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del punto de monitoreo.', max_digits=9, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el punto.')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del punto.')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que registró este punto de monitoreo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_monitoreo_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Monitoreo',
                'verbose_name_plural': 'Puntos de Monitoreo',
                'ordering': ['nombre'],
            },
        ),
    ]
