# Generated by Django 5.2.4 on 2025-08-05 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Código del departamento, ej: 'INF', 'FIS', 'MAT'", max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo del departamento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del departamento', null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Número de la asignatura, ej: '182', '120'", max_length=10)),
                ('nombre', models.CharField(help_text='Nombre de la asignatura', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la asignatura', null=True)),
                ('departamento', models.ForeignKey(help_text='Departamento al que pertenece la asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='quickstart.departamento')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['departamento__codigo', 'numero'],
                'unique_together': {('departamento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='horarios/')),
                ('tipo_documento', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('csv', 'CSV (.csv)'), ('txt', 'Texto (.txt)'), ('pdf', 'PDF (.pdf)'), ('imagen', 'Imagen (.png, .jpg)')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('texto_extraido', models.TextField(blank=True)),
                ('eventos_detectados', models.JSONField(default=list)),
                ('confianza_ia', models.FloatField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('intentos_procesamiento', models.IntegerField(default=0)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_horario', to='quickstart.asignatura')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Horario',
                'verbose_name_plural': 'Documentos de Horarios',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del evento', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada del evento')),
                ('date', models.DateTimeField(help_text='Fecha y hora del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del evento')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('created_by', models.ForeignKey(help_text='Administrador que creó este evento', on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventoExtraido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_detectado', models.CharField(max_length=300)),
                ('fecha_detectada', models.DateTimeField()),
                ('descripcion_detectada', models.TextField(blank=True)),
                ('confianza_general', models.FloatField(default=0.0)),
                ('verificado', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='quickstart.documentohorario')),
                ('evento_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_extraido', to='quickstart.event')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Extraído',
                'verbose_name_plural': 'Eventos Extraídos',
                'ordering': ['fecha_detectada'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la pregunta', max_length=300)),
                ('contenido', models.TextField(help_text='Contenido detallado de la pregunta')),
                ('nombre_autor', models.CharField(blank=True, help_text='Nombre a mostrar del autor (si es anónimo o alias)', max_length=100, null=True)),
                ('es_anonima', models.BooleanField(default=False, help_text='Si la pregunta es anónima')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('esta_resuelta', models.BooleanField(default=False, help_text='Indica si la pregunta ya tiene respuesta satisfactoria')),
                ('asignatura', models.ForeignKey(help_text='Asignatura a la que pertenece la pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='quickstart.asignatura')),
                ('autor', models.ForeignKey(blank=True, help_text='Usuario que realizó la pregunta (opcional para preguntas anónimas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PuntoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del lugar, ej: 'Biblioteca', 'Auditorio', 'Laboratorio A1'", max_length=150, unique=True)),
                ('temperatura_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Última temperatura registrada en grados Celsius', max_digits=5, null=True)),
                ('fecha_ultima_temperatura', models.DateTimeField(blank=True, help_text='Fecha y hora de la última lectura de temperatura', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el punto.')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del punto.')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que registró este punto de monitoreo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_monitoreo_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Monitoreo',
                'verbose_name_plural': 'Puntos de Monitoreo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido de la respuesta')),
                ('nombre_autor', models.CharField(blank=True, help_text='Nombre a mostrar del autor (si es anónimo o alias)', max_length=100, null=True)),
                ('es_anonima', models.BooleanField(default=False, help_text='Si la respuesta es anónima')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('es_respuesta_aceptada', models.BooleanField(default=False, help_text='Si es la respuesta aceptada por el autor de la pregunta')),
                ('autor', models.ForeignKey(blank=True, help_text='Usuario que realizó la respuesta (opcional para respuestas anónimas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(help_text='Pregunta a la que responde', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='quickstart.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['-es_respuesta_aceptada', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_propuesto', models.CharField(help_text='Código propuesto, ej: TEL-312, FIS-140', max_length=20)),
                ('nombre_propuesto', models.CharField(help_text='Nombre de la asignatura', max_length=200)),
                ('descripcion_propuesta', models.TextField(blank=True, help_text='Descripción opcional')),
                ('departamento_codigo', models.CharField(help_text='Código del departamento, ej: TEL, FIS', max_length=10)),
                ('numero_asignatura', models.CharField(help_text='Número de la asignatura, ej: 312', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comentarios_revision', models.TextField(blank=True)),
                ('asignatura_creada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='quickstart.asignatura')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asignatura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Asignatura',
                'verbose_name_plural': 'Solicitudes de Asignaturas',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('codigo_propuesto',)},
            },
        ),
    ]
