# Generated by Django 5.2.1 on 2025-07-09 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del evento', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada del evento')),
                ('date', models.DateTimeField(help_text='Fecha y hora del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del evento')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('created_by', models.ForeignKey(help_text='Administrador que creó este evento', on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
    ]
