# Generated by Django 5.2.1 on 2025-07-19 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Código del departamento, ej: 'INF', 'FIS', 'MAT'", max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo del departamento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del departamento', null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Número de la asignatura, ej: '182', '120'", max_length=10)),
                ('nombre', models.CharField(help_text='Nombre de la asignatura', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la asignatura', null=True)),
                ('departamento', models.ForeignKey(help_text='Departamento al que pertenece la asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='quickstart.departamento')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['departamento__codigo', 'numero'],
                'unique_together': {('departamento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la pregunta', max_length=300)),
                ('contenido', models.TextField(help_text='Contenido detallado de la pregunta')),
                ('nombre_autor', models.CharField(blank=True, help_text='Nombre a mostrar del autor (si es anónimo o alias)', max_length=100, null=True)),
                ('es_anonima', models.BooleanField(default=False, help_text='Si la pregunta es anónima')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('esta_resuelta', models.BooleanField(default=False, help_text='Indica si la pregunta ya tiene respuesta satisfactoria')),
                ('asignatura', models.ForeignKey(help_text='Asignatura a la que pertenece la pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='quickstart.asignatura')),
                ('autor', models.ForeignKey(blank=True, help_text='Usuario que realizó la pregunta (opcional para preguntas anónimas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido de la respuesta')),
                ('nombre_autor', models.CharField(blank=True, help_text='Nombre a mostrar del autor (si es anónimo o alias)', max_length=100, null=True)),
                ('es_anonima', models.BooleanField(default=False, help_text='Si la respuesta es anónima')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('es_respuesta_aceptada', models.BooleanField(default=False, help_text='Si es la respuesta aceptada por el autor de la pregunta')),
                ('autor', models.ForeignKey(blank=True, help_text='Usuario que realizó la respuesta (opcional para respuestas anónimas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(help_text='Pregunta a la que responde', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='quickstart.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['-es_respuesta_aceptada', '-fecha_creacion'],
            },
        ),
    ]
