# Generated by Django 5.2.1 on 2025-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_departamento_asignatura_pregunta_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntomonitoreo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='puntomonitoreo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='puntomonitoreo',
            name='longitud',
        ),
        migrations.AddField(
            model_name='puntomonitoreo',
            name='fecha_ultima_temperatura',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última lectura de temperatura', null=True),
        ),
        migrations.AddField(
            model_name='puntomonitoreo',
            name='temperatura_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Última temperatura registrada en grados Celsius', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='puntomonitoreo',
            name='nombre',
            field=models.CharField(help_text="Nombre del lugar, ej: 'Biblioteca', 'Auditorio', 'Laboratorio A1'", max_length=150, unique=True),
        ),
    ]
